config/routes.rb
Twitter::Application.routes.draw do

  resources :users, except: [:edit] do
    member do
      get 'confirm' #/users/:id/column
    end  
  end

  get '/profile', to: 'users#edit'

  resources :tweets, except: [:edit, :update]

  get '/login', to: 'logins#new_session', as: 'sign_in' 
  post '/login', to: 'logins#create_session'
  get '/logout', to: 'logins#logout', as: 'sign_out'

  root 'tweets#index'

  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :content,  presence: true, length: { maximum: 140 }		
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :handle, presence: true
	mount_uploader :avatar, AvatarUploader
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def check_user_login
    @current_user = User.find(session[:user_id])
  end

    protected
    def not_found
      flash[:error] = "You need to log in to tweet."
      redirect_to sign_in_path
    end
  

    
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new_session
  	@user = User.new
  end

  def create_session

  	user = User.find_by(email: params[:user][:email])
  	if user
  		session[:user_id] = user.id 
      session[:password] = user.password
  		redirect_to user_path(user)
  	else
  		redirect_to new_user_path
  	end
  end		

  def logout
  end

 
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new_session
  	@user = User.new
  end

  def create_session

  	#user = User.find_by(email: params[:user][:email])
    user = User.find_by(email: params[:user][:email])
    
     	if user && user.authenticate(params[:user][:password])
        session[:user_id] = user.id 
        redirect_to user_path(user)
  	  else
        flash[:error] = 'Invalid email/password combination'
     	  redirect_to sign_in_path

      end

  end
  	
  

  def logout
      session[:user_id] = nil
      #reset_session
      redirect_to sign_in_path
  end

 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :check_user_login, except: [:index]
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end


  def destroy
  end

  def new
    @tweet = Tweet.new
  end

  def create

    @tweet = Tweet.new(tweet_params)
   
    @tweet.user = @current_user
        
        respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully posted.' }
        format.json { render action: 'show', status: :created, location: @tweet }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  private

 

  def tweet_params
    params.require(:tweet).permit(:content)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user_login, except: [:new,:create]

  def index
  end

	def new
		@user = User.new
	end	

	def show
    	@user = User.find(params[:id])
      @tweet = Tweet.new
  	end

  def create
    	@user = User.new(user_params)
     
      if @user.save
       UserMailer.confirm_email(@user).deliver #"confirm_email" method under => app/mailers/user_mailer.rb
       redirect_to user_path(@user)
      else
      render 'new'
    end
  end

  def update
    @current_user.update_attributes(user_params)
    redirect_to user_path(@current_user)
  end  

  def confirm
    head :ok
  end

  private

  	def user_params
    	params.require(:user).permit(:name, :email, :handle, :password, :avatar, :remove_avatar, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logins_helper.rb
module LoginsHelper

def signed_in?
	 	!session[:user_id].nil?
end

end

app/helpers/tweets_helper.rb
module TweetsHelper

	# def tweet_length (tweet)
	# 	largo = tweet.content.length
	# 	if largo > 1
	# 		"This tweet has #{largo} characters."
	# 	elsif largo == 1
	# 		"This tweet has 1 character."
	# 	end
	# end

	def tweet_length (tweet)
		tlength = tweet.content.length
		return "This tweet has 1 character." if tlength == 1
		"This tweet has #{tlength} characters."
	end

	# def user_handle (tweet)
	# 	if session[:user_id] != nil
	# 	tweet.user.handle
	# 	end
	# end	

	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "FAKE TWITTER", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          
          <% if signed_in? %>
      
            <li> <%= link_to "Sign out", sign_out_path %>
            </li>
           
            <li>
                <%= link_to "Profile", profile_path %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign in", sign_in_path %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %> 
 <div class="container">

 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

 <%= yield %>     
</div>
</body>
</html>

app/views/login/new_session.html.erb
<h1>Log in to shitty Twitter</h1>

<%= form_for @user, url:login_path do |f| %>

<div>
	e-mail: <%= f.text_field :email %>
</div>

<div>
	Password: <%= f.password_field :password %>
</div>

<%= f.submit "Log in" %>

<% end %>

app/views/logins/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>

app/views/logins/new_session.html.erb
<h1>Log in to shitty Twitter</h1>

<%= form_for @user, url:login_path do |f| %>

<div>
	e-mail: <%= f.text_field :email %>
</div>

<div>
	Password: <%= f.text_field :password %>
</div>
<div>
  <% if @user.errors.any? %>	
  <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
  <% end %>
</div>      

<%= f.submit "Log in" %>

<div>New user? <%= link_to 'Sign up', new_user_path %> now!</div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tweets/_tweet_form.html.erb
<%= form_for @tweet do |t| %>

  <% if @tweet.errors.any? %>

    <div>
    	<!-- id = "error_explanation" -->
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being posted:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<div>Tweet: <%= t.text_area :content %></div>

<div><%= t.submit %></div>

<% end %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/index.html.erb
<h2>All the tweets</h2>

<% @tweets.each do |tweet| %>
<div class='entry_users'>
<h4><%= link_to "#{tweet.content}", tweet_path(tweet) %></h4>
<div><%= tweet_length(tweet) %> Posted by @<%= tweet.user.handle %></div>
<div>This tweet was posted <%= time_ago_in_words(tweet.created_at) %> ago.</div>
</div>
<br>
<% end %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<!-- rendering form here -->
<%= form_for @tweet do |t| %>

  <% if @tweet.errors.any? %>

    <div>
    	<!-- id = "error_explanation" -->
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being posted:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<div>Tweet: <%= t.text_area :content %></div>

<div><%= t.submit %></div>

<% end %>
<!-- rendering form here -->

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h4><%= @tweet.content %> - Posted by @<%= @tweet.user.handle %></h4>
<h5>This tweet was posted <%= time_ago_in_words(@tweet.created_at) %> ago.</h5>

<h4><%= link_to "All Tweets", tweets_path %></h4>
<h4><%= link_to "See all user's tweets", user_path(@tweet.user) %></h4>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Profile</h1>

<%= form_for @current_user, html: {multipart: true} do |f| %>
<div>Your Name: <%= f.text_field :name %></div>
<div>Handle: <%= f.text_field :handle %></div>
<div>Avatar: <%= f.file_field :avatar %></div>

<div><%= f.check_box :remove_avatar %>
	<%= f.label :remove_avatar %>
</div>

<%= f.submit "Save Settings" %>

<% end %>

app/views/users/new.html.erb
<h1>Welcome to Fake Twitter</h1>
<h3>Possibly the shittiest fake twitter experience on the web.</h3>

<%= form_for @user do |f| %>
 <%= render 'shared/error_messages' %>

<div>
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div>
	<%= f.label :"e-mail" %>
	<%= f.text_field :email %>
</div>

<div>
	<%= f.label :handle %>
	<%= f.text_field :handle %>
</div>

<div>
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>

<div>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>



<div><%= f.submit %></div>

<% end %>

app/views/users/show.html.erb
<div>
<%= image_tag(@user.avatar_url, :width => 100) if @user.avatar_url.present? %>
@<%= @user.handle %> - <%= @user.name %>
</div>

<%= render "/tweets/tweet_form" %>


<% @user.tweets.each do |tweet| %>
<div class="entry_user">
	<div><span class="label"><%= tweet.created_at.to_formatted_s(:short)%></span></div>

	<div class="ttext"><h4><%= link_to tweet.content, tweet_path(tweet) %></h4></div>
</div>
<% end %>